services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - stage_network

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6377:6379"
    networks:
      - stage_network

  springboot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stage_container
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - redis
    networks:
      - stage_network

volumes:
  postgres_data:

networks:
  stage_network:
    driver: bridge
