services:
  postgres:
    image: postgres:13
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - network
    restart: always

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6377:6379"
    networks:
      - network
    restart: always

  stage-nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: stage-nginx
    ports:
      - "80:80"
    networks:
      - network
    restart: always

  springboot:
    build:
      context: .
      dockerfile: Dockerfile_dev
    container_name: stage_container
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
    ports:
      - "8081:8081"
    volumes:
      - ./src:/app/src
      - ./pom.xml:/app/pom.xml
      - ~/.m2:/root/.m2  # Cache Maven dependencies
    depends_on:
      - postgres
      - redis
    networks:
      - network
    restart: always
    command: mvn clean package -DskipTests && java -jar /app/target/stage-0.0.1-SNAPSHOT.jar

volumes:
  postgres_data:

networks:
  network:
    driver: bridge
