FROM maven:3.9.1-eclipse-temurin-17-alpine

WORKDIR /app

COPY . .

COPY target/stage-*.jar /app/stage.jar


ENV SPRING_PROFILES_ACTIVE=local


EXPOSE 8081

ENTRYPOINT ["java", "-jar", "stage.jar"]
#CMD ["mvn", "clean", "spring-boot:run"]

