spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    url: ${SPRING_DATASOURCE_URL:default}
    username: ${SPRING_DATASOURCE_USERNAME:default}
    password: ${SPRING_DATASOURCE_PASSWORD:default}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans=true: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      database: 0
      host: redis_container
      port: 6379

cloud:
  aws:
    credentials:
      access-key: ${AWS_ACCESS_KEY_ID:default}
      secret-key: ${AWS_SECRET_KEY:default}
    region:
      static: ${AWS_REGION:default}
    s3:
      bucket: ${AWS_BUCKET_NAME:default}
      endpoint: ${AWS_S3_END_POINT:default}

server:
  port: 8081

logging:
  level:
    org.springframework.web: INFO
    org.springframework.web.filter.CommonsRequestLoggingFilter: INFO